spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 0556559704Islam
    url: jdbc:mysql://localhost:3307/task-manger
    username: dark3
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
